In [1]:
import pandas as pd
import numpy as np
pd.plotting.register_matplotlib_converters()
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sklearn
print("Setup Complete")

Setup Complete


In [2]:
train_path = "/kaggle/input/data-clean-1/data_clean_1.csv"

train_data = pd.read_csv(train_path)

In [3]:
train_data.head()

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0           FDA15         9.30          Low Fat         0.016047   
1           DRC01         5.92          Regular         0.019278   
2           FDN15        17.50          Low Fat         0.016760   
3           FDX07        19.20          Regular         0.000000   
4           NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998      Medium               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052

In [4]:
train_data.shape

(14204, 12)

In [5]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                14204 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                14204 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          14204 non-null  float64
dtypes: float64(4), int64(1), object(7)
memory usage: 1.3+ MB


In [6]:
train_data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [7]:
train_data.nunique()

Item_Identifier               1559
Item_Weight                    416
Item_Fat_Content                 5
Item_Visibility              13006
Item_Type                       16
Item_MRP                      8052
Outlet_Identifier               10
Outlet_Establishment_Year        9
Outlet_Size                      3
Outlet_Location_Type             3
Outlet_Type                      4
Item_Outlet_Sales             3493
dtype: int64

In [8]:
train_data.describe()

Item_Weight  Item_Visibility      Item_MRP  Outlet_Establishment_Year  \
count  14204.000000     14204.000000  14204.000000               14204.000000   
mean      12.792854         0.065953    141.004977                1997.830681   
std        4.234226         0.051459     62.086938                   8.371664   
min        4.555000         0.000000     31.290000                1985.000000   
25%        9.300000         0.027036     94.012000                1987.000000   
50%       12.792854         0.054021    142.247000                1999.000000   
75%       16.000000         0.094037    185.855600                2004.000000   
max       21.350000         0.328391    266.888400                2009.000000   

       Item_Outlet_Sales  
count       14204.000000  
mean         2026.522094  
std          1335.388924  
min            33.290000  
25%          1468.089000  
50%          1794.331000  
75%          2163.184200  
max         13086.964800

**Modify *Item_Visibility***
> We noticed that the minimum value here is 0, which makes no practical sense.

In [9]:
#Determine average visibility of a product
visibility_avg = train_data.pivot_table(values='Item_Visibility', index='Item_Identifier')

#Impute 0 values with mean visibility of that product:
zero_values = (train_data['Item_Visibility'] == 0)

print('Number of 0 values initially: %d'%sum(zero_values))
train_data.loc[zero_values,'Item_Visibility'] = train_data.loc[zero_values,'Item_Identifier'].apply(lambda x: visibility_avg.loc[x])
print('Number of 0 values after modification: %d'%sum(train_data['Item_Visibility'] == 0))

Number of 0 values initially: 879
Number of 0 values after modification: 0


In [10]:
train_data["Item_Visibility"].describe()

count    14204.000000
mean         0.069710
std          0.049728
min          0.003575
25%          0.031145
50%          0.057194
75%          0.096930
max          0.328391
Name: Item_Visibility, dtype: float64

**Create a broad category of *Item_Type***

In [11]:
train_data.groupby(["Item_Identifier","Item_Type"]).size()

Item_Identifier  Item_Type         
DRA12            Soft Drinks            9
DRA24            Soft Drinks           10
DRA59            Soft Drinks           10
DRB01            Soft Drinks            8
DRB13            Soft Drinks            9
                                       ..
NCZ30            Household             10
NCZ41            Health and Hygiene     8
NCZ42            Household             10
NCZ53            Health and Hygiene     9
NCZ54            Household             10
Length: 1559, dtype: int64

> We can clearly observe that the First 2 characters of the Item ID is same for the One kind of Item Type. Example: DR is the code for Soft Drinks, NC is the code of Non- Consumable Products and FD is for Food products

In [12]:
#Get the first two characters of ID:
train_data['Item_Type_Combined'] = train_data['Item_Identifier'].apply(lambda x: x[0:2])

#Rename them to more intuitive categories:
train_data['Item_Type_Combined'] = train_data['Item_Type_Combined'].map({'FD':'Food',
                                                             'NC':'Non-Consumable',
                                                             'DR':'Drinks'})
print(train_data['Item_Type_Combined'].value_counts())

Food              10201
Non-Consumable     2686
Drinks             1317
Name: Item_Type_Combined, dtype: int64


**Modify categories of *Item_Fat_Content***

In [13]:
train_data['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular', 'low fat', 'LF', 'reg'], dtype=object)

In [14]:
#Change categories of low fat:
print('Original Categories:')
print(train_data['Item_Fat_Content'].value_counts())

print('\nModified Categories:')
train_data['Item_Fat_Content'] = train_data['Item_Fat_Content'].replace({'LF':'Low Fat','reg':'Regular','low fat':'Low Fat'})
print(train_data['Item_Fat_Content'].value_counts())

Original Categories:
Low Fat    8485
Regular    4824
LF          522
reg         195
low fat     178
Name: Item_Fat_Content, dtype: int64

Modified Categories:
Low Fat    9185
Regular    5019
Name: Item_Fat_Content, dtype: int64


# **Label Encoding**

In [15]:
train_data['Item_Fat_Content'].unique()

array(['Low Fat', 'Regular'], dtype=object)

In [16]:
train_data['Outlet_Size'].unique()

array(['Medium', 'High', 'Small'], dtype=object)

In [17]:
train_data['Outlet_Location_Type'].unique()

array(['Tier 1', 'Tier 3', 'Tier 2'], dtype=object)

In [18]:
train_data['Outlet_Type'].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

In [19]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

In [20]:
train_data['Outlet_Size']= label_encoder.fit_transform(train_data['Outlet_Size'])
train_data['Outlet_Size'].unique()

array([1, 0, 2])

In [21]:
train_data['Outlet_Location_Type']= label_encoder.fit_transform(train_data['Outlet_Location_Type'])
train_data['Outlet_Location_Type'].unique()

array([0, 2, 1])

In [22]:
train_data['Outlet_Type']= label_encoder.fit_transform(train_data['Outlet_Type'])
train_data['Outlet_Type'].unique()

array([1, 2, 0, 3])

In [23]:
train_data['Item_Fat_Content']= label_encoder.fit_transform(train_data['Item_Fat_Content'])
train_data['Item_Fat_Content'].unique()

array([0, 1])

In [24]:
train_data['Item_Type_Combined']= label_encoder.fit_transform(train_data['Item_Type_Combined'])
train_data['Item_Type_Combined'].unique()

array([1, 0, 2])

In [25]:
train_data.shape

(14204, 13)

# **One-Hot Encoding**

In [26]:
#One Hot Coding:
train_data = pd.get_dummies(train_data, columns=['Item_Fat_Content','Outlet_Size','Outlet_Location_Type','Outlet_Type','Item_Type_Combined'])

In [27]:
train_data.head()

Item_Identifier  Item_Weight  Item_Visibility              Item_Type  \
0           FDA15         9.30         0.016047                  Dairy   
1           DRC01         5.92         0.019278            Soft Drinks   
2           FDN15        17.50         0.016760                   Meat   
3           FDX07        19.20         0.017834  Fruits and Vegetables   
4           NCD19         8.93         0.009780              Household   

   Item_MRP Outlet_Identifier  Outlet_Establishment_Year  Item_Outlet_Sales  \
0  249.8092            OUT049                       1999          3735.1380   
1   48.2692            OUT018                       2009           443.4228   
2  141.6180            OUT049                       1999          2097.2700   
3  182.0950            OUT010                       1998           732.3800   
4   53.8614            OUT013                       1987           994.7052   

   Item_Fat_Content_0  Item_Fat_Content_1  ...  Outlet_Location_Type_0  \
0                   1                   0  ...                       1   
1                   0                   1  ...                       0   
2                   1                   0  ...                       1   
3                   0                   1  ...                       0   
4                   1                   0  ...                       0   

   Outlet_Location_Type_1  Outlet_Location_Type_2  Outlet_Type_0  \
0                       0                       0              0   
1                       0                       1              0   
2                       0                       0              0   
3                       0                       1              1   
4                       0                       1              0   

   Outlet_Type_1  Outlet_Type_2  Outlet_Type_3  Item_Type_Combined_0  \
0              1              0              0                     0   
1              0              1              0                     1   
2              1              0              0                     0   
3              0              0              0                     0   
4              1              0              0                     0   

   Item_Type_Combined_1  Item_Type_Combined_2  
0                     1                     0  
1                     0                     0  
2                     1                     0  
3                     1                     0  
4                     0                     1  

[5 rows x 23 columns]

In [28]:
train_data.shape

(14204, 23)

In [29]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                14204 non-null  float64
 2   Item_Visibility            14204 non-null  float64
 3   Item_Type                  14204 non-null  object 
 4   Item_MRP                   14204 non-null  float64
 5   Outlet_Identifier          14204 non-null  object 
 6   Outlet_Establishment_Year  14204 non-null  int64  
 7   Item_Outlet_Sales          14204 non-null  float64
 8   Item_Fat_Content_0         14204 non-null  uint8  
 9   Item_Fat_Content_1         14204 non-null  uint8  
 10  Outlet_Size_0              14204 non-null  uint8  
 11  Outlet_Size_1              14204 non-null  uint8  
 12  Outlet_Size_2              14204 non-null  uint8  
 13  Outlet_Location_Type_0     14204 non-null  uin

In [30]:
train_data.to_csv("data_clean_2.csv")